[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-fruit-salad"

[wallpaper]
directory = "~/dotfiles/files/wallpapers"
fill_color = "#000000"
edge_smoothness = 0.05
transition = ["fade", "wipe", "disc", "stripes", "zoom", "honeycomb"]
transition_duration = 1500.0

[wallpaper.default]
path = "~/dotfiles/files/wallpapers/a.jpg"

[wallpaper.automation]
enabled = false
interval_seconds = 300
order = "random"

[theme.templates]
enable_builtin_templates = true
builtin_ids = ["sway", "alacritty", "gtk3", "gtk4", "qt"]

[audio]
enable_overdrive = false
enable_sounds = false
sound_volume = 0.5

[bar.default]
background_opacity = 0.93
margin_edge = 4
margin_ends = 4
radius = 12
position = "bottom"
auto_hide = false
capsule = false
show_on_workspace_switch = true
widget_spacing = 6
padding = 14
thickness = 34
reserve_space = true
start = ["launcher", "clock", "cpu", "ram", "active_window", "media"]
center = ["workspaces"]
end = [
  "tray",
  "notifications",
  "battery",
  "volume",
  "brightness",
  "control-center",
]

[widget.clock]
format = "{:%H:%M %a, %b %d}"
tooltip_format = "{:%H:%M %a, %b %d}"

[widget.cpu]
type = "sysmon"
stat = "cpu_usage"

[widget.ram]
type = "sysmon"
stat = "ram_used"

[widget.active_window]
max_length = 145.0
display = "icon_and_text"

[widget.media]
artist_first = true
max_length = 145.0
title_scroll = "on_hover"

[battery]
warning_threshold = 20

[brightness]
enable_ddcutil = false

[calendar]
enabled = true

[control_center]
hidden_tabs = ["monitor"]
width = 700
sidebar = "compact"
sidebar_section = "compact"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "wallpaper"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[desktop_widgets]
enabled = false

[idle]
pre_action_fade_seconds = 5.0

[idle.behavior."screen-off"]
enabled = true
timeout = 600.0

[keybinds]
validate = ["Return", "Enter"]
cancel = ["Esc"]
delete = ["Del"]
left = ["Left"]
right = ["Right"]
up = ["Up"]
down = ["Down"]

[location]
auto_locate = true
address = "Miryang"

[lockscreen]
blurred_desktop = false
blur_intensity = 0.0
tint_intensity = 0.0

[nightlight]
enabled = false
temperature_day = 6500
temperature_night = 4000

[notification]
background_opacity = 1.0
position = "top_right"

[osd]
background_opacity = 1.0
position = "top_right"
enabled = true

[plugins]
auto_update = false

[shell]
font_family = "Inter"
telemetry_enabled = false
corner_radius_scale = 0.25
clipboard_auto_paste = "off"
show_location = true

[shell.animation]
enabled = true
speed = 2.0

[shell.panel]
launcher_placement = "floating"
launcher_position = "center"
control_center_placement = "attached"
open_near_click_control_center = true

[shell.session]
grid = false
show_shortcuts = true

[[shell.session.actions]]
action = "lock"
shortcut = "1"
countdown_seconds = 10.0

[[shell.session.actions]]
action = "suspend"
shortcut = "2"
countdown_seconds = 10.0

[[shell.session.actions]]
action = "command"
command = "systemctl hibernate"
label = "Hibernate"
shortcut = "3"
countdown_seconds = 10.0

[[shell.session.actions]]
action = "reboot"
shortcut = "4"
countdown_seconds = 10.0

[[shell.session.actions]]
action = "logout"
shortcut = "5"
countdown_seconds = 10.0

[[shell.session.actions]]
action = "shutdown"
shortcut = "6"
countdown_seconds = 10.0
variant = "destructive"

[[shell.session.actions]]
action = "command"
command = "systemctl reboot --firmware-setup"
label = "Reboot to UEFI"
shortcut = "7"
countdown_seconds = 10.0

[system.monitor]
cpu_usage_activity_threshold = 80.0
cpu_usage_critical_threshold = 90.0
cpu_temp_activity_threshold = 80.0
cpu_temp_critical_threshold = 90.0
ram_pct_activity_threshold = 80.0
ram_pct_critical_threshold = 90.0
swap_pct_activity_threshold = 80.0
swap_pct_critical_threshold = 90.0
disk_used_activity_threshold = 80.0
disk_used_critical_threshold = 90.0
disk_free_activity_threshold = 20.0
disk_free_critical_threshold = 10.0
gpu_usage_activity_threshold = 80.0
gpu_usage_critical_threshold = 90.0
gpu_temp_activity_threshold = 80.0
gpu_temp_critical_threshold = 90.0

[weather]
enabled = true
unit = "metric"
effects = true
